### ISSUE TITLE
Integrate Census Information

### ISSUE THREAD

**Issue by JuanCPDev** [isabelllauwu/Digital-Divide#2]
Use the census information provided to include more information either on the existing maps or graphs.
https://broadbandusa.maps.arcgis.com/apps/webappviewer/index.html?id=e2b4907376b548f892672ef6afbc0da5

This issue should be split into sub-tickets if needed.

**Comment by estefysc** [comment]
I have added a couple of functions to obtain a geoJSON file of Orange County census tracts. 655ed6308b8e66c393b3d0c5451d120051b5614c 

And a function to obtain a file with median annual income for each Orange County census tract.
845188f153ac1b8346ad363f95e033c653e6ff82
