### ISSUE TITLE
move BGimage styling from main to css page

### ISSUE THREAD

**Issue by JuanCPDev** [isabelllauwu/Digital-Divide#5]
add class tag to BGimage and move styling to css page. BGimage refers to the variable in the main python file.

![Screenshot 2022-09-15 163947](https://user-images.githubusercontent.com/86272014/190504371-cb612493-eb41-4aaf-bac1-e5392aeb446a.png)
![Screenshot 2022-09-15 163631](https://user-images.githubusercontent.com/86272014/190503852-89d7dc9b-309c-45e4-bc88-810a80a58eeb.png)
![Screenshot 2022-09-15 1636312](https://user-images.githubusercontent.com/86272014/190503942-e85774fe-dbd4-4a20-b926-132161f809e1.png)

**Comment by isabelllauwu** [comment]
currently working on this
